jobs:
  validate_partial:
    executor: salesforce-sfdx/default
    steps:
      - checkout
      - salesforce-sfdx/install
      - salesforce-sfdx/auth:
          defaultusername: ${SFDX_USERNAME_PARTIAL}
          consumerKey: SFDX_CONSUMER_KEY_PARTIAL
          instanceUrl: https://test.salesforce.com
      - run:
          command: >
            sfdx force:source:deploy -u "${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BRANCH}" -m "ApexClass, ApexPage, ApexComponent, ApexTrigger, AuraDefinitionBundle, LightningComponentBundle"  -l RunLocalTests -w 33 --loglevel info;
          name: Creating SFDX Project and deploying sources to Partial Environment.
  validate_prod:
    executor: salesforce-sfdx/default
    steps:
     - checkout
     - salesforce-sfdx/install
     - salesforce-sfdx/auth:
          defaultusername: ${SFDX_USERNAME_PROD}
          consumerKey: SFDX_CONSUMER_KEY_PROD
          instanceUrl: https://login.salesforce.com
     - run:
         command: >
           mkdir /tmp/test-results/;
           sfdx force:apex:test:run -u "${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BRANCH}" -c -r junit  > /tmp/test-results/testrun_beforeDeployment.xml;
           sfdx force:source:deploy -u "${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BRANCH}" -m "ApexClass, ApexPage, ApexComponent, ApexTrigger, AuraDefinitionBundle, LightningComponentBundle"  -l RunLocalTests -w 33 --loglevel info;
           mkdir /tmp/artifacts;
           sfdx force:apex:test:run -u "${CIRCLE_PROJECT_REPONAME}-${CIRCLE_BRANCH}" -c -r junit  > /tmp/test-results/testrun_afterDeployment.xml;
           sfdx force:apex:log:get > /tmp/artifacts/testrundebug.log
         name: Creating SFDX Project and deploying sources to Production Environment
     - store_test_results:
        path: /tmp/test-results
     - store_artifacts:
          path: /tmp/artifacts
orbs:
  salesforce-sfdx: circleci/salesforce-sfdx@2.2.0
version: 2.1
workflows:
  hotfix_run:
    jobs:
      - validate_partial: # << the job to conditionally run based on the filter-by-branch-name.
          filters:
            branches:
              only: /^hotfix.*/
      - validate_prod: # << the job to conditionally run based on the filter-by-branch-name.
          filters:
            branches:
              only: /^hotfix.*/
  Development_run:
    jobs:
      - validate_partial: # << the job to conditionally run based on the filter-by-branch-name.
          filters:
            branches:
              only:
                - master
          name: Validate Partial from Master branch
  partial_run:
    jobs:
      - validate_prod: # << the job to conditionally run based on the filter-by-branch-name.
          filters:
            branches:
              only: partial
